# Generated by Django 4.1.1 on 2022-12-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aot',
            options={},
        ),
        migrations.AlterField(
            model_name='aot',
            name='name',
            field=models.CharField(default='character', help_text='Character Name', max_length=64),
        ),
    ]
